// ===========================================================================
// This file has been generated by
// Rats! Parser Generator, version 2.4.0,
// (C) 2004-2014 Robert Grimm,
// on Quarta-feira, 15 de Março de 2017 at 20:33:34.
// Edit at your own risk.
// ===========================================================================

import java.io.Reader;
import java.io.IOException;

import xtc.util.Pair;

import xtc.parser.ParserBase;
import xtc.parser.Column;
import xtc.parser.Result;
import xtc.parser.SemanticValue;
import xtc.parser.ParseError;

/**
 * Packrat parser for grammar <code>option</code>.
 *
 * <p />This class has been generated by the <i>Rats!</i> parser
 * generator, version 2.4.0, (C) 2004-2014 Robert Grimm.
 */
public final class option extends ParserBase {

  // =========================================================================

  /** Memoization table column. */
  static final class optionColumn extends Column {
    Result fws;
  }

  // =========================================================================

  /**
   * Create a new packrat parser.
   *
   * @param reader The reader.
   * @param file The file name.
   */
  public option(final Reader reader, final String file) {
    super(reader, file);
  }

  /**
   * Create a new packrat parser.
   *
   * @param reader The file reader.
   * @param file The file name.
   * @param size The file size.
   */
  public option(final Reader reader, final String file, final int size) {
    super(reader, file, size);
  }

  // =========================================================================

  protected Column newColumn() {
    return new optionColumn();
  }

  // =========================================================================

  /**
   * Parse nonterminal option.option.
   *
   * @param yyStart The index.
   * @return The result.
   * @throws IOException Signals an I/O error.
   */
  public Result poption(final int yyStart) throws IOException {
    int        yyC;
    int        yyIndex;
    Result     yyResult;
    int        yyRepetition1;
    int        yyOption1;
    Void       yyValue;
    ParseError yyError = ParseError.DUMMY;

    // Alternative 1.

    yyC = character(yyStart);
    if ('o' == yyC) {
      yyIndex = yyStart + 1;

      yyC = character(yyIndex);
      if ('p' == yyC) {
        yyIndex = yyIndex + 1;

        yyC = character(yyIndex);
        if ('t' == yyC) {
          yyIndex = yyIndex + 1;

          yyC = character(yyIndex);
          if ('i' == yyC) {
            yyIndex = yyIndex + 1;

            yyC = character(yyIndex);
            if ('o' == yyC) {
              yyIndex = yyIndex + 1;

              yyC = character(yyIndex);
              if ('n' == yyC) {
                yyIndex = yyIndex + 1;

                yyC = character(yyIndex);
                if ('s' == yyC) {
                  yyIndex = yyIndex + 1;

                  yyOption1  = yyIndex;

                  yyResult = pws(yyOption1);
                  yyError  = yyResult.select(yyError, yyOption1);
                  if (yyResult.hasValue()) {

                    yyOption1  = yyResult.index;
                  }

                  yyC = character(yyOption1);
                  if ('{' == yyC) {
                    yyIndex = yyOption1 + 1;

                    yyOption1  = yyIndex;

                    yyResult = pws(yyOption1);
                    yyError  = yyResult.select(yyError, yyOption1);
                    if (yyResult.hasValue()) {

                      yyOption1  = yyResult.index;
                    }

                    yyRepetition1 = yyOption1;
                    while (true) {

                      yyResult = pgrammar_opt(yyRepetition1);
                      yyError  = yyResult.select(yyError, yyRepetition1);
                      if (yyResult.hasValue()) {

                        yyC = character(yyResult.index);
                        if (';' == yyC) {
                          yyIndex = yyResult.index + 1;

                          yyRepetition1 = yyIndex;
                          continue;
                        }
                      }
                      break;
                    }

                    yyOption1  = yyRepetition1;

                    yyResult = pws(yyOption1);
                    yyError  = yyResult.select(yyError, yyOption1);
                    if (yyResult.hasValue()) {

                      yyOption1  = yyResult.index;
                    }

                    yyC = character(yyOption1);
                    if ('}' == yyC) {
                      yyIndex = yyOption1 + 1;

                      yyValue = null;

                      return new SemanticValue(yyValue, yyIndex, yyError);
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    // Done.
    yyError = yyError.select("option expected", yyStart);
    return yyError;
  }

  // =========================================================================

  /**
   * Parse nonterminal option.grammar_opt.
   *
   * @param yyStart The index.
   * @return The result.
   * @throws IOException Signals an I/O error.
   */
  public Result pgrammar_opt(final int yyStart) throws IOException {
    int        yyC;
    int        yyIndex;
    Result     yyResult;
    int        yyOption1;
    Void       yyValue;
    ParseError yyError = ParseError.DUMMY;

    // Alternative 1.

    yyC = character(yyStart);
    if (-1 != yyC) {
      yyIndex = yyStart + 1;

      switch (yyC) {
      case 'i':
        {
          yyC = character(yyIndex);
          if (-1 != yyC) {
            yyIndex = yyIndex + 1;
            if ('s' == yyC) {

              yyC = character(yyIndex);
              if (-1 != yyC) {
                yyIndex = yyIndex + 1;
                if ('A' == yyC) {

                  yyC = character(yyIndex);
                  if (-1 != yyC) {
                    yyIndex = yyIndex + 1;
                    if ('d' == yyC) {

                      yyC = character(yyIndex);
                      if (-1 != yyC) {
                        yyIndex = yyIndex + 1;
                        if ('a' == yyC) {

                          yyC = character(yyIndex);
                          if (-1 != yyC) {
                            yyIndex = yyIndex + 1;
                            if ('p' == yyC) {

                              yyC = character(yyIndex);
                              if (-1 != yyC) {
                                yyIndex = yyIndex + 1;
                                if ('t' == yyC) {

                                  yyC = character(yyIndex);
                                  if (-1 != yyC) {
                                    yyIndex = yyIndex + 1;
                                    if ('a' == yyC) {

                                      yyC = character(yyIndex);
                                      if (-1 != yyC) {
                                        yyIndex = yyIndex + 1;
                                        if ('b' == yyC) {

                                          yyC = character(yyIndex);
                                          if (-1 != yyC) {
                                            yyIndex = yyIndex + 1;
                                            if ('l' == yyC) {

                                              yyC = character(yyIndex);
                                              if (-1 != yyC) {
                                                yyIndex = yyIndex + 1;
                                                if ('e' == yyC) {

                                                  yyOption1  = yyIndex;

                                                  yyResult = pws(yyOption1);
                                                  yyError  = 
                                                    yyResult.select(yyError, yyOption1);
                                                  if (yyResult.hasValue()) {

                                                    yyOption1  = yyResult.index;
                                                  }

                                                  yyC = character(yyOption1);
                                                  if ('=' == yyC) {
                                                    yyIndex = yyOption1 + 1;

                                                    yyOption1  = yyIndex;

                                                    yyResult = pws(yyOption1);
                                                    yyError  = 
                                                      yyResult.select(yyError, yyOption1);
                                                    if (yyResult.hasValue()) {

                                                      yyOption1  = yyResult.index;
                                                    }

                                                    final int yyChoice1 = yyOption1;

                                                    // Nested alternative 1.

                                                    yyC = 
                                                      character(yyChoice1);
                                                    if (-1 != yyC) {
                                                      yyIndex = yyChoice1 + 1;

                                                      switch (yyC) {
                                                      case 't':
                                                        {
                                                          yyC = 
                                                            character(yyIndex);
                                                          if (-1 != yyC) {
                                                            yyIndex = yyIndex + 1;
                                                            if ('r' == yyC) {

                                                              yyC = 
                                                                character(yyIndex);
                                                              if (-1 != yyC) {
                                                                yyIndex = yyIndex + 1;
                                                                if ('u' == yyC) {

                                                                  yyC = 
                                                                    character(yyIndex);
                                                                  if (-1 != yyC) {
                                                                    yyIndex = yyIndex + 1;
                                                                    if ('e' == yyC) {

                                                                      yyValue = null;

                                                                      return new SemanticValue(yyValue, yyIndex, yyError);
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                        break;

                                                      case 'f':
                                                        {
                                                          yyC = 
                                                            character(yyIndex);
                                                          if (-1 != yyC) {
                                                            yyIndex = yyIndex + 1;
                                                            if ('a' == yyC) {

                                                              yyC = 
                                                                character(yyIndex);
                                                              if (-1 != yyC) {
                                                                yyIndex = yyIndex + 1;
                                                                if ('l' == yyC) {

                                                                  yyC = 
                                                                    character(yyIndex);
                                                                  if (-1 != yyC) {
                                                                    yyIndex = yyIndex + 1;
                                                                    if ('s' == yyC) {

                                                                      yyC = 
                                                                        character(yyIndex);
                                                                      if (-1 != yyC) {
                                                                        yyIndex = yyIndex + 1;
                                                                        if ('e' == yyC) {

                                                                          yyValue = null;

                                                                          return new SemanticValue(yyValue, yyIndex, yyError);
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                        break;

                                                      default:
                                                        /* No match. */
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        break;

      case 'm':
        {
          yyC = character(yyIndex);
          if (-1 != yyC) {
            yyIndex = yyIndex + 1;
            if ('e' == yyC) {

              yyC = character(yyIndex);
              if (-1 != yyC) {
                yyIndex = yyIndex + 1;
                if ('m' == yyC) {

                  yyC = character(yyIndex);
                  if (-1 != yyC) {
                    yyIndex = yyIndex + 1;
                    if ('o' == yyC) {

                      yyC = character(yyIndex);
                      if (-1 != yyC) {
                        yyIndex = yyIndex + 1;
                        if ('i' == yyC) {

                          yyC = character(yyIndex);
                          if (-1 != yyC) {
                            yyIndex = yyIndex + 1;
                            if ('z' == yyC) {

                              yyC = character(yyIndex);
                              if (-1 != yyC) {
                                yyIndex = yyIndex + 1;
                                if ('e' == yyC) {

                                  yyOption1  = yyIndex;

                                  yyResult = pws(yyOption1);
                                  yyError  = 
                                    yyResult.select(yyError, yyOption1);
                                  if (yyResult.hasValue()) {

                                    yyOption1  = yyResult.index;
                                  }

                                  yyC = character(yyOption1);
                                  if ('=' == yyC) {
                                    yyIndex = yyOption1 + 1;

                                    yyOption1  = yyIndex;

                                    yyResult = pws(yyOption1);
                                    yyError  = 
                                      yyResult.select(yyError, yyOption1);
                                    if (yyResult.hasValue()) {

                                      yyOption1  = yyResult.index;
                                    }

                                    final int yyChoice1 = yyOption1;

                                    // Nested alternative 1.

                                    yyC = character(yyChoice1);
                                    if (-1 != yyC) {
                                      yyIndex = yyChoice1 + 1;

                                      switch (yyC) {
                                      case 't':
                                        {
                                          yyC = character(yyIndex);
                                          if (-1 != yyC) {
                                            yyIndex = yyIndex + 1;
                                            if ('r' == yyC) {

                                              yyC = character(yyIndex);
                                              if (-1 != yyC) {
                                                yyIndex = yyIndex + 1;
                                                if ('u' == yyC) {

                                                  yyC = character(yyIndex);
                                                  if (-1 != yyC) {
                                                    yyIndex = yyIndex + 1;
                                                    if ('e' == yyC) {

                                                      yyValue = null;

                                                      return new SemanticValue(yyValue, yyIndex, yyError);
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                        break;

                                      case 'f':
                                        {
                                          yyC = character(yyIndex);
                                          if (-1 != yyC) {
                                            yyIndex = yyIndex + 1;
                                            if ('a' == yyC) {

                                              yyC = character(yyIndex);
                                              if (-1 != yyC) {
                                                yyIndex = yyIndex + 1;
                                                if ('l' == yyC) {

                                                  yyC = character(yyIndex);
                                                  if (-1 != yyC) {
                                                    yyIndex = yyIndex + 1;
                                                    if ('s' == yyC) {

                                                      yyC = 
                                                        character(yyIndex);
                                                      if (-1 != yyC) {
                                                        yyIndex = yyIndex + 1;
                                                        if ('e' == yyC) {

                                                          yyValue = null;

                                                          return new SemanticValue(yyValue, yyIndex, yyError);
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                        break;

                                      default:
                                        /* No match. */
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        break;

      case 'e':
        {
          yyC = character(yyIndex);
          if (-1 != yyC) {
            yyIndex = yyIndex + 1;
            if ('n' == yyC) {

              yyC = character(yyIndex);
              if (-1 != yyC) {
                yyIndex = yyIndex + 1;
                if ('v' == yyC) {

                  yyC = character(yyIndex);
                  if (-1 != yyC) {
                    yyIndex = yyIndex + 1;
                    if ('S' == yyC) {

                      yyC = character(yyIndex);
                      if (-1 != yyC) {
                        yyIndex = yyIndex + 1;
                        if ('e' == yyC) {

                          yyC = character(yyIndex);
                          if (-1 != yyC) {
                            yyIndex = yyIndex + 1;
                            if ('m' == yyC) {

                              yyC = character(yyIndex);
                              if (-1 != yyC) {
                                yyIndex = yyIndex + 1;
                                if ('a' == yyC) {

                                  yyC = character(yyIndex);
                                  if (-1 != yyC) {
                                    yyIndex = yyIndex + 1;
                                    if ('n' == yyC) {

                                      yyC = character(yyIndex);
                                      if (-1 != yyC) {
                                        yyIndex = yyIndex + 1;
                                        if ('t' == yyC) {

                                          yyC = character(yyIndex);
                                          if (-1 != yyC) {
                                            yyIndex = yyIndex + 1;
                                            if ('i' == yyC) {

                                              yyC = character(yyIndex);
                                              if (-1 != yyC) {
                                                yyIndex = yyIndex + 1;
                                                if ('c' == yyC) {

                                                  yyC = character(yyIndex);
                                                  if (-1 != yyC) {
                                                    yyIndex = yyIndex + 1;
                                                    if ('s' == yyC) {

                                                      yyOption1  = yyIndex;

                                                      yyResult = 
                                                        pws(yyOption1);
                                                      yyError  = 
                                                        yyResult.select(yyError, yyOption1);
                                                      if (yyResult.hasValue()) {

                                                        yyOption1  = yyResult.index;
                                                      }

                                                      yyC = 
                                                        character(yyOption1);
                                                      if ('=' == yyC) {
                                                        yyIndex = yyOption1 + 1;

                                                        yyOption1  = yyIndex;

                                                        yyResult = 
                                                          pws(yyOption1);
                                                        yyError  = 
                                                          yyResult.select(yyError, yyOption1);
                                                        if (yyResult.hasValue()) {

                                                          yyOption1  = yyResult.index;
                                                        }

                                                        final int yyChoice1 = yyOption1;

                                                        // Nested alternative 1.

                                                        yyC = 
                                                          character(yyChoice1);
                                                        if (-1 != yyC) {
                                                          yyIndex = yyChoice1 + 1;

                                                          switch (yyC) {
                                                          case 's':
                                                            {
                                                              yyC = 
                                                                character(yyIndex);
                                                              if (-1 != yyC) {
                                                                yyIndex = yyIndex + 1;
                                                                if ('i' == yyC) {

                                                                  yyC = 
                                                                    character(yyIndex);
                                                                  if (-1 != yyC) {
                                                                    yyIndex = yyIndex + 1;
                                                                    if ('m' == yyC) {

                                                                      yyC = 
                                                                        character(yyIndex);
                                                                      if (-1 != yyC) {
                                                                        yyIndex = yyIndex + 1;
                                                                        if ('p' == yyC) {

                                                                          yyC = 
                                                                            character(yyIndex);
                                                                          if (-1 != yyC) {
                                                                            yyIndex = yyIndex + 1;
                                                                            if ('l' == yyC) {

                                                                              yyC = 
                                                                                character(yyIndex);
                                                                              if (-1 != yyC) {
                                                                                yyIndex = yyIndex + 1;
                                                                                if ('e' == yyC) {

                                                                                  yyValue = null;

                                                                                  return new SemanticValue(yyValue, yyIndex, yyError);
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                            break;

                                                          case 'd':
                                                            {
                                                              yyC = 
                                                                character(yyIndex);
                                                              if (-1 != yyC) {
                                                                yyIndex = yyIndex + 1;
                                                                if ('i' == yyC) {

                                                                  yyC = 
                                                                    character(yyIndex);
                                                                  if (-1 != yyC) {
                                                                    yyIndex = yyIndex + 1;
                                                                    if ('s' == yyC) {

                                                                      yyC = 
                                                                        character(yyIndex);
                                                                      if (-1 != yyC) {
                                                                        yyIndex = yyIndex + 1;
                                                                        if ('c' == yyC) {

                                                                          yyC = 
                                                                            character(yyIndex);
                                                                          if (-1 != yyC) {
                                                                            yyIndex = yyIndex + 1;
                                                                            if ('a' == yyC) {

                                                                              yyC = 
                                                                                character(yyIndex);
                                                                              if (-1 != yyC) {
                                                                                yyIndex = yyIndex + 1;
                                                                                if ('r' == yyC) {

                                                                                  yyC = 
                                                                                    character(yyIndex);
                                                                                  if (-1 != yyC) {
                                                                                    yyIndex = yyIndex + 1;
                                                                                    if ('d' == yyC) {

                                                                                      yyC = 
                                                                                        character(yyIndex);
                                                                                      if (-1 != yyC) {
                                                                                        yyIndex = yyIndex + 1;
                                                                                        if ('C' == yyC) {

                                                                                          yyC = 
                                                                                            character(yyIndex);
                                                                                          if (-1 != yyC) {
                                                                                            yyIndex = yyIndex + 1;
                                                                                            if ('h' == yyC) {

                                                                                              yyC = 
                                                                                                character(yyIndex);
                                                                                              if (-1 != yyC) {
                                                                                                yyIndex = yyIndex + 1;
                                                                                                if ('a' == yyC) {

                                                                                                  yyC = 
                                                                                                    character(yyIndex);
                                                                                                  if (-1 != yyC) {
                                                                                                    yyIndex = yyIndex + 1;
                                                                                                    if ('n' == yyC) {

                                                                                                      yyC = 
                                                                                                        character(yyIndex);
                                                                                                      if (-1 != yyC) {
                                                                                                        yyIndex = yyIndex + 1;
                                                                                                        if ('g' == yyC) {

                                                                                                          yyC = 
                                                                                                            character(yyIndex);
                                                                                                          if (-1 != yyC) {
                                                                                                            yyIndex = yyIndex + 1;
                                                                                                            if ('e' == yyC) {

                                                                                                              yyC = 
                                                                                                                character(yyIndex);
                                                                                                              if (-1 != yyC) {
                                                                                                                yyIndex = yyIndex + 1;
                                                                                                                if ('W' == yyC) {

                                                                                                                  yyC = 
                                                                                                                    character(yyIndex);
                                                                                                                  if (-1 != yyC) {
                                                                                                                    yyIndex = yyIndex + 1;
                                                                                                                    if ('h' == yyC) {

                                                                                                                      yyC = 
                                                                                                                        character(yyIndex);
                                                                                                                      if (-1 != yyC) {
                                                                                                                        yyIndex = yyIndex + 1;
                                                                                                                        if ('e' == yyC) {

                                                                                                                          yyC = 
                                                                                                                            character(yyIndex);
                                                                                                                          if (-1 != yyC) {
                                                                                                                            yyIndex = yyIndex + 1;
                                                                                                                            if ('n' == yyC) {

                                                                                                                              yyC = 
                                                                                                                                character(yyIndex);
                                                                                                                              if (-1 != yyC) {
                                                                                                                                yyIndex = yyIndex + 1;
                                                                                                                                if ('F' == yyC) {

                                                                                                                                  yyC = 
                                                                                                                                    character(yyIndex);
                                                                                                                                  if (-1 != yyC) {
                                                                                                                                    yyIndex = yyIndex + 1;
                                                                                                                                    if ('a' == yyC) {

                                                                                                                                      yyC = 
                                                                                                                                        character(yyIndex);
                                                                                                                                      if (-1 != yyC) {
                                                                                                                                        yyIndex = yyIndex + 1;
                                                                                                                                        if ('i' == yyC) {

                                                                                                                                          yyC = 
                                                                                                                                            character(yyIndex);
                                                                                                                                          if (-1 != yyC) {
                                                                                                                                            yyIndex = yyIndex + 1;
                                                                                                                                            if ('l' == yyC) {

                                                                                                                                              yyValue = null;

                                                                                                                                              return new SemanticValue(yyValue, yyIndex, yyError);
                                                                                                                                            }
                                                                                                                                          }
                                                                                                                                        }
                                                                                                                                      }
                                                                                                                                    }
                                                                                                                                  }
                                                                                                                                }
                                                                                                                              }
                                                                                                                            }
                                                                                                                          }
                                                                                                                        }
                                                                                                                      }
                                                                                                                    }
                                                                                                                  }
                                                                                                                }
                                                                                                              }
                                                                                                            }
                                                                                                          }
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                  }
                                                                                                }
                                                                                              }
                                                                                            }
                                                                                          }
                                                                                        }
                                                                                      }
                                                                                    }
                                                                                  }
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                            break;

                                                          default:
                                                            /* No match. */
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        break;

      default:
        /* No match. */
      }
    }

    // Done.
    yyError = yyError.select("grammar_opt expected", yyStart);
    return yyError;
  }

  // =========================================================================

  /**
   * Parse nonterminal option.header.
   *
   * @param yyStart The index.
   * @return The result.
   * @throws IOException Signals an I/O error.
   */
  public Result pheader(final int yyStart) throws IOException {
    int        yyC;
    int        yyIndex;
    Result     yyResult;
    int        yyOption1;
    Void       yyValue;
    ParseError yyError = ParseError.DUMMY;

    // Alternative 1.

    yyC = character(yyStart);
    if ('h' == yyC) {
      yyIndex = yyStart + 1;

      yyC = character(yyIndex);
      if ('e' == yyC) {
        yyIndex = yyIndex + 1;

        yyC = character(yyIndex);
        if ('a' == yyC) {
          yyIndex = yyIndex + 1;

          yyC = character(yyIndex);
          if ('d' == yyC) {
            yyIndex = yyIndex + 1;

            yyC = character(yyIndex);
            if ('e' == yyC) {
              yyIndex = yyIndex + 1;

              yyC = character(yyIndex);
              if ('r' == yyC) {
                yyIndex = yyIndex + 1;

                yyOption1  = yyIndex;

                yyResult = pws(yyOption1);
                yyError  = yyResult.select(yyError, yyOption1);
                if (yyResult.hasValue()) {

                  yyOption1  = yyResult.index;
                }

                yyC = character(yyOption1);
                if ('{' == yyC) {
                  yyIndex = yyOption1 + 1;

                  yyOption1  = yyIndex;

                  yyResult = pws(yyOption1);
                  yyError  = yyResult.select(yyError, yyOption1);
                  if (yyResult.hasValue()) {

                    yyOption1  = yyResult.index;
                  }

                  yyResult = ph_text(yyOption1);
                  yyError  = yyResult.select(yyError);
                  if (yyResult.hasValue()) {

                    yyOption1  = yyResult.index;

                    yyResult = pws(yyOption1);
                    yyError  = yyResult.select(yyError, yyOption1);
                    if (yyResult.hasValue()) {

                      yyOption1  = yyResult.index;
                    }

                    yyC = character(yyOption1);
                    if ('}' == yyC) {
                      yyIndex = yyOption1 + 1;

                      yyResult = pws(yyIndex);
                      yyError  = yyResult.select(yyError);
                      if (yyResult.hasValue()) {

                        yyValue = null;

                        return yyResult.createValue(yyValue, yyError);
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    // Done.
    yyError = yyError.select("header expected", yyStart);
    return yyError;
  }

  // =========================================================================

  /**
   * Parse nonterminal option.h_text.
   *
   * @param yyStart The index.
   * @return The result.
   * @throws IOException Signals an I/O error.
   */
  public Result ph_text(final int yyStart) throws IOException {
    int        yyC;
    int        yyIndex;
    int        yyRepetition1;
    Void       yyValue;
    ParseError yyError = ParseError.DUMMY;

    // Alternative 1.

    yyRepetition1 = yyStart;
    while (true) {

      yyC = character(yyRepetition1);
      if (-1 != yyC) {
        yyIndex = yyRepetition1 + 1;

        yyRepetition1 = yyIndex;
        continue;
      }
      break;
    }

    yyValue = null;

    return new SemanticValue(yyValue, yyRepetition1, yyError);
  }

  // =========================================================================

  /**
   * Parse nonterminal spacing.ws.
   *
   * @param yyStart The index.
   * @return The result.
   * @throws IOException Signals an I/O error.
   */
  private Result pws(final int yyStart) throws IOException {
    optionColumn yyColumn = (optionColumn)column(yyStart);
    if (null == yyColumn.fws) yyColumn.fws = pws$1(yyStart);
    return yyColumn.fws;
  }

  /** Actually parse spacing.ws. */
  private Result pws$1(final int yyStart) throws IOException {
    int        yyC;
    int        yyIndex;
    Result     yyResult;
    int        yyOption1;
    Void       yyValue;
    ParseError yyError = ParseError.DUMMY;

    // Alternative 1.

    yyC = character(yyStart);
    if (-1 != yyC) {
      yyIndex = yyStart + 1;

      switch (yyC) {
      case ' ':
        {
          yyResult = pws(yyIndex);
          yyError  = yyResult.select(yyError);
          if (yyResult.hasValue()) {

            yyValue = null;

            return yyResult.createValue(yyValue, yyError);
          }
        }
        break;

      case '\t':
        {
          yyResult = pws(yyIndex);
          yyError  = yyResult.select(yyError);
          if (yyResult.hasValue()) {

            yyValue = null;

            return yyResult.createValue(yyValue, yyError);
          }
        }
        break;

      default:
        /* No match. */
      }
    }

    // Alternative 2.

    yyOption1  = yyStart;

    yyC = character(yyOption1);
    if ('\r' == yyC) {
      yyIndex = yyOption1 + 1;

      yyOption1  = yyIndex;
    }

    yyC = character(yyOption1);
    if ('\n' == yyC) {
      yyIndex = yyOption1 + 1;

      yyResult = pws(yyIndex);
      yyError  = yyResult.select(yyError);
      if (yyResult.hasValue()) {

        yyValue = null;

        return yyResult.createValue(yyValue, yyError);
      }
    }

    // Alternative 3.

    yyC = character(yyStart);
    if (-1 != yyC) {
      yyIndex = yyStart + 1;

      switch (yyC) {
      case '\r':
        {
          yyResult = pws(yyIndex);
          yyError  = yyResult.select(yyError);
          if (yyResult.hasValue()) {

            yyValue = null;

            return yyResult.createValue(yyValue, yyError);
          }
        }
        break;

      case ' ':
        {
          yyValue = null;

          return new SemanticValue(yyValue, yyIndex, yyError);
        }

      case '\t':
        {
          yyValue = null;

          return new SemanticValue(yyValue, yyIndex, yyError);
        }

      default:
        /* No match. */
      }
    }

    // Alternative 4.

    yyOption1  = yyStart;

    yyC = character(yyOption1);
    if ('\r' == yyC) {
      yyIndex = yyOption1 + 1;

      yyOption1  = yyIndex;
    }

    yyC = character(yyOption1);
    if ('\n' == yyC) {
      yyIndex = yyOption1 + 1;

      yyValue = null;

      return new SemanticValue(yyValue, yyIndex, yyError);
    }

    // Alternative 5.

    yyC = character(yyStart);
    if ('\r' == yyC) {
      yyIndex = yyStart + 1;

      yyValue = null;

      return new SemanticValue(yyValue, yyIndex, yyError);
    }

    // Done.
    yyError = yyError.select("ws expected", yyStart);
    return yyError;
  }

}
